### ISSUE TITLE
Backend ISSUE #1

### ISSUE THREAD

**Issue by mindovermattr** [mindovermattr/vue-kanban#4]
@killkih 
При попытке добавить карточку, вылетает ошибка:
![image](https://github.com/user-attachments/assets/afc9db9e-394e-4458-b27e-f7069a251968)
Вероятно, дело в том, что в create методе забыл дописать категорию
![image](https://github.com/user-attachments/assets/9b115f9d-b121-4db1-8438-612c13fd28fc)

**Comment by killkih** [comment]
<img width="1077" alt="Снимок экрана 2024-10-04 в 10 33 46" src="https://github.com/user-attachments/assets/0cfc8f23-8e13-42e4-8957-e7ac185a4f7d">

Ошибки тут нет, в body запроса нужно передавать не category, а category_id!
