### ISSUE TITLE
Frontend issue #1

### ISSUE THREAD

**Issue by killkih** [mindovermattr/vue-kanban#5]
![изображение](https://github.com/user-attachments/assets/e736a0ba-a4b3-4859-9c6e-950b53fc53be)
При создании таски, отображается 2 карточки, в базе данных в действительности хранится 1, перезапуск сервера не дает результата.
Скриншот базы:
<img width="776" alt="изображение" src="https://github.com/user-attachments/assets/7ab21847-0b11-4d90-bf1d-638db8e7e1ec">

**Comment by mindovermattr** [comment]
Исправил, почекай в новой ветке

**Comment by killkih** [comment]
Всё работает, можешь мержить!
